### ISSUE TITLE
ERROR: Amounts received/calculated does not match - Back (browser) issue

### ISSUE THREAD

**Issue by d33x** [wl-online-payments-direct/plugin-prestashop#8]
When a customer places an order, selects a carrier and arrives on the Worldline payment page, if they go back via the browser and change carrier (with a different price), the transaction on Worldline is not updated and the customer is therefore asked to pay less or more than expected.

Hence the error: ERROR: Amounts received/calculated does not match

Partly similar to #2

**Comment by d33x** [comment]
@Worldline-PrestaShop-Team @WorldlinePrestashopTeam @WorldlineShoppingCarts ?

**Comment by d33x** [comment]
@Worldline-plugins-1 @WorldlinePrestashopTeam Is this resolved by 1.4.8 or not?

> Fix order total webhook issue

**Comment by worldline-direct-support-team** [comment]
Hello @d33x,

Thank you for revisiting this topic.

We wanted to let you know that this issue still exists in version 1.4.8 of the Worldline module; however, the good news is that we’ve reproduced this issue in our local environment, and our team is working on a fix.

We will let you know as soon as we have some updates on the status of this fix.

Kind regards.

**Comment by worldline-direct-support-team** [comment]
Hello @d33x,

This is just a quick note to let you know that we expect to release a new plugin version at the start of next week.

We will let you know as soon as it is available.

Kind regards.

**Comment by worldline-direct-support-team** [comment]
Hello @d33x,

Thank you for your patience,

Please note that the new plugin version 2.0.13 has been released. Therefore, we will close this issue.

New plugin version can be found here:https://github.com/wl-online-payments-direct/plugin-prestashop-8/releases/tag/v2.0.13 

Feel free to reopen the issue if you have any additional questions.

Kind regards.
